name: ARCHE-Ingest

on:
  workflow_dispatch:
    inputs:
      database_id:
        type: number
        description: '(Required) Database ID as number'
        required: true
        default: 0
      project_name:
        type: string
        description: '(Required) Project Name as string'
        required: true
        default: 'konradbayer'
      arche_instance:
        type: choice
        options:
          - arche-curation.acdh-dev
          - arche.acdh
        description: '(Required) ARCHE instance as choice (e.g., arche-curation.acdh-dev, arche-prod.acdh.oeaw.ac.at)'
        required: true
        default: 'arche-curation.acdh-dev'

jobs:
  build_pages:
    name: Ingest Data into ARCHE
    runs-on: ubuntu-latest
    env:
      ANT_OPTS: -Xmx5g
      REDMINE_ID: 27229
      ARCHE_INSTANCE: ${{ github.event.inputs.arche_instance }}
      ARCHE_INSTANCE_NAME: ${{ github.event.inputs.arche_instance == 'arche-curation.acdh-dev' && 'Curation' || 'Production' }}
      OUTPUT_DIR: rdf
      BASEROW_TOKEN: ${{ secrets.BASEROW_TOKEN }}
      BASEROW_DB_ID: ${{ github.event.inputs.database_id }}
      BASEROW_USER: ${{ secrets.BASEROW_USER }}
      BASEROW_PW: ${{ secrets.BASEROW_PW }}
      PROJECT_NAME: ${{ github.event.inputs.project_name }}
      ARCHE_LOGIN: ${{ secrets.ARCHE_LOGIN }}
      ARCHE_PASSWORD: ${{ secrets.ARCHE_PASSWORD }}
    steps:
    - name: Perform Checkout
      uses: actions/checkout@v7
    # - name: Set up Python environment
    #   uses: actions/setup-python@v7
    #   with:
    #     python-version: "3.12"
    # - name: Install dependencies
    #   run: |
    #     python -m pip install --upgrade pip
    #     pip install uv
    # - name: Baserow Dump and TEI/XML Download
    #   run: |
    #     uv run src/baserow_dump.py
    # - name: Creating ARCHE constants ttl file
    #   run: |
    #     uv run src/arche_constants.py
    - name: ingestion dependencies
      run: |
        composer require "acdh-oeaw/arche-ingest:^1"
    - name: Fetch WF-URL
      run: |
        echo "RUN_URL=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" >> $GITHUB_ENV
    - name: ingest arche metadata topcol, col, res
      run: |
        echo "STEP=Upload AIP to $ARCHE_INSTANCE_NAME Instance" >> $GITHUB_ENV
        # vendor/bin/arche-delete-triples $OUTPUT_DIR/delete_facsimiles_creator.ttl https://$ARCHE_INSTANCE.oeaw.ac.at/api $ARCHE_LOGIN $ARCHE_PASSWORD
        # sleep 60
        vendor/bin/arche-import-metadata $OUTPUT_DIR/arche_constants_crawler.ttl https://$ARCHE_INSTANCE.oeaw.ac.at/api $ARCHE_LOGIN $ARCHE_PASSWORD --retriesOnConflict 25
        # vendor/bin/arche-update-redmine --token ${{ secrets.REDMINE_TOKEN }} --append "$RUN_URL" $REDMINE_ID "Upload AIP to $ARCHE_INSTANCE_NAME Instance"
    # - name: on failure
    #   if: ${{ failure() }}
    #   run: |
    #     vendor/bin/arche-update-redmine --token ${{ secrets.REDMINE_TOKEN }} --append "$RUN_URL" --statusCode 1 $REDMINE_ID "$STEP"