name: ARCHE-Ingest

on:
  workflow_dispatch:

jobs:
  build_pages:
    name: Ingest Data into ARCHE
    runs-on: ubuntu-latest
    env:
      ANT_OPTS: -Xmx5g
      REDMINE_ID: 27229
      ARCHE_INSTANCE: arche-curation.acdh-dev
      ARCHE_INSTANCE_NAME: Curation
      PROJECT_NAME : konradbayer
      OUTPUT_DIR: rdf
    steps:
    - name: Perform Checkout
      uses: actions/checkout@v7
    - name: ingestion dependencies
      run: |
        composer require "acdh-oeaw/arche-ingest:^1"
    - name: Fetch WF-URL
      run: |
        echo "RUN_URL=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" >> $GITHUB_ENV
    - name: ingest arche metadata topcol, col, res
      run: |
        echo 'STEP=Upload AIP to ${ARCHE_INSTANCE_NAME} Instance' >> $GITHUB_ENV
        # vendor/bin/arche-delete-triples ${OUTPUT_DIR}/delete_facsimiles_creator.ttl https://${ARCHE_INSTANCE}.oeaw.ac.at/api ${{secrets.ARCHE_LOGIN}} ${{secrets.ARCHE_PASSWORD}}
        # sleep 60
        vendor/bin/arche-import-metadata ${OUTPUT_DIR}/arche_constants.ttl https://${ARCHE_INSTANCE}.oeaw.ac.at/api ${{secrets.ARCHE_LOGIN}} ${{secrets.ARCHE_PASSWORD}} --retriesOnConflict 25
        vendor/bin/arche-update-redmine --token ${{ secrets.REDMINE_TOKEN }} --append "$RUN_URL" $REDMINE_ID 'Upload AIP to ${ARCHE_INSTANCE_NAME} Instance'
    - name: on failure
      if: ${{ failure() }}
      run: |
        vendor/bin/arche-update-redmine --token ${{ secrets.REDMINE_TOKEN }} --append "$RUN_URL" --statusCode 1 $REDMINE_ID "$STEP"